### ISSUE TITLE
Create a new Intake catalog for this (final) decadal release (r4)

### ISSUE THREAD

**Issue by agstephens** [roocs/catalog-maker#9]
Please set up a new (hopefully final) decadal Intake catalog from this file (listing dataset IDs):

https://raw.githubusercontent.com/cp4cds/c3s_34g_qc_results/master/releases/r4/final/r4_final.txt

You might need to rename "CMIP6" to "c3s-cmip6" to match other catalogs.

**Comment by ellesmith88** [comment]
Closed via https://github.com/cp4cds/c3s_34g_manifests/pull/20
